name: sqlite3-to-mysql
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py310h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1t=h7f8727e_0
  - pip=23.0.1=py310h06a4308_0
  - python=3.10.9=h7a1cb2a_2
  - readline=8.2=h5eee18b_0
  - setuptools=65.6.3=py310h06a4308_0
  - sqlite=3.40.1=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2022g=h04d1e81_0
  - wheel=0.38.4=py310h06a4308_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - click==8.1.3
      - mysql-connector-python==8.0.29
      - packaging==23.1
      - protobuf==3.20.3
      - pytimeparse==1.1.8
      - pytimeparse2==1.7.1
      - simplejson==3.19.1
      - six==1.16.0
      - sqlite3-to-mysql==1.4.16
      - tabulate==0.9.0
      - tqdm==4.65.0
      - typing-extensions==4.7.1
      - unidecode==1.3.6
